### ISSUE TITLE
"Email already exists" validator

### ISSUE THREAD

**Issue by ericclemmons** [thejameskyle/revalid#3]
Do you have an idea or plans on how `revalid` would support this?

This simple, async use-case is where most validators lack architectural support for async validations, but it's an incredibly common scenario.  Here are some common examples:

- Checking if the account is already registered.
- Calling the backend to ensure the user doesn't re-use a previous password. (USAA does this)
- Checking if the repo already exists:

  > 
![screen shot 2016-06-13 at 10 07 58 am](https://cloud.githubusercontent.com/assets/15182/16012377/d00d075e-314e-11e6-9feb-b97655f9d113.png)

One possibility would be relying on function arity, similar to how you can add `next` to test cases in Mocha:

```js
function isNewRepo(fieldName) {
  return function(value, fields, next) {
    fetch("/api/repos/" + value).then(function(response) {
      const { status, statusText } = response;

      next(status === "200" ? false : {
        type: "isNewRepo",
        fieldname,
        status,
        statusText,
        value,
      });
    }).catch(...);
  };
}
```

...or if the response returns a `Promise`.

Anyway, the project looks interesting and definitely scratches an itch!  I just wanted to see if this something you'd consider a PR for.

Thanks @thejameskyle!

**Comment by thejameskyle** [comment]
Revalid likely will never support async validations itself. However, you could easily extend the API to make it so.

Revalid is less about solving every possible type of validation and more about setting you up with an interface for writing composable validations.

The reason I don't want to get into async validations is because that inherently ties you to the rest of the system. It's likely that you have an entire workflow for dealing with requests and how that interacts with your UI. It's probably more complicated to tie that to your client-side validations.

**Comment by ericclemmons** [comment]
@thejameskyle I understand.  If you can point me in the direction to how to extend the API to support async, that'd be great!

Feel free to close.

**Comment by thejameskyle** [comment]
I don't know that its a great idea to extend the API directly– depending on your use case.

In my experience it has always been better to write one off logic for async validation, so I can't really related.
